### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by rodericj**

### CODE REVIEW

**Review by mcritz — CHANGES_REQUESTED** [review]
If you’re gathering & using data generated by the user’s behavior you’ll need to include a privacy policy TOC. And you’ll want to be GDPR compliant.

Request a link somewhere in the UI that displays a GDPR compliant TOC visible to the user.

**Comment by rodericj** [comment]
Right. Currently this doesn’t track user behavior though. Only Apple behavior. Does that change anything?

**Comment by mcritz** [comment]
@rodericj  I think that’s a decision I’d like to have the team make. I’m OK with whatever for now. I know there’s a pragmatic need to troubleshoot app behavior in beta.

But…
- the behavior of `applicationWillLaunch` is being tracked. Not sure if that’s user behavior (e.g. user tapped on app icon) or not.
- Before we launch, If the app is sending data to a server somewhere, then we’ll want to be sure we’re telling users what is being sent, even if _we think_ it’s innocuous, users might not think so. We’ll need to add the TOC screen before we go to App Store with telemetry on.

We should remove the telemetry before launch or add a TOC screen. Either way, a backlog item should be written.

Edit: or the team can accept that `applicationWillLaunch` isn’t capturing user behavior.

**Comment by rodericj** [comment]
Closing. I think there are more private ways we can do this.

**Pull request closed without merging**
