### PR TITLE
Fix the notification button constraints in EventsFeedViewController

### LINKED ISSUE #92: Notification Button Off-Screen
The notification button is partially off the screen for pre-iPhone X phones.
Simulator Screen Shot - iPhone 8 Plus - 2019-05-10 at 12 19 08

### PR DESCRIPTION
**Pull request by jerrytdev**
Closes #92

### CODE REVIEW

**Review by rodericj — CHANGES_REQUESTED** [review]
Would you mind just swapping the order of the anchors and keeping the constants as positives?

**Comment by rodericj** [comment]
Basically when I set these constraints I put them in the wrong order. I should’ve constrained  a to b but instead I constrained b to a

**Comment by jerrytdev** [comment]
I understand keeping positive anchors, but IMO Apple made a mistake with the API considering the right and bottom constraints are reversed (positive/negative) from the edge inset API.

**Comment by rodericj** [comment]
Ok. Sounds good to me.

**Pull request merged**
