### PR TITLE
Fix app sharing - closes #119

### LINKED ISSUE #119: Customize the share content based on destination
When sharing (from the group view) we're sharing a string. Based on the destination we need to probably set the URL to nil.

See: `activitiyViewController itemForActivityType`

### PR DESCRIPTION
**Pull request by jerrytdev**

### CODE REVIEW

**Comment by rodericj** [comment]
Pretty good. This fixed the airdrop issue. Could we perhaps limit the sharing so it doesn't allow you to share with file sharing apps? I was able to share this to iCloud Drive and it's just the CTA text with no link or URL.

**Comment by rodericj** [comment]
I've not seen "closes" in the commit message title. Does that work? I sort of thought it needed to be in the body. This doesn't seem to differentiate: https://help.github.com/en/articles/closing-issues-using-keywords

**Review by rodericj — CHANGES_REQUESTED** [review]
See comment above. Looks like we can still share to files which is probably not appropriate for link sharing.

**Comment by rodericj** [comment]
What happened?

**Comment by jerrytdev** [comment]
I ended up doing a very simple change, at least for the time being; given
the changes since I did the original pull-request I did a fresh clone.

**Pull request closed without merging**
