### PR TITLE
Created AnimationHelper to change the status of highlighted Group & Feed cells.

### PR DESCRIPTION
**Pull request by milesofmichael**
Thanks Ethan for the feedback.  Since Group and Feed cells are Collection and Table view cells respectively, I made AnimationHelper a subclass of UIView.  The delay issue in the GroupCollectionView was fixed by toggling delaysContentTouches.  However, a really quick tap can still bypass the highlighted state for the ImageBasedCollectionViewCell.  Any ideas?

### CODE REVIEW

**Comment by milesofmichael** [comment]
HighlightedCell

**Review by EthanSchatzline — CHANGES_REQUESTED** [review]
This is looking better, but I have a few questions:
1. Why does `AnimationHelper` subclass UIView? It isn't a view, but rather a helper
   - There's a solution where this is a UIView subclass (probably named something different like `BouncyView: UIView`), but the CollectionViewCell and TableViewCell's main view would have to be a subclass of that. And then in `setHighlighted:` you could call the animate method on that view.
2. Why is the animation method on `AnimationHelper` an instance method rather than just a class method? 
    - Instance Method: `[[AnimationHelper new] animateView:self.detailStackContainer highlighted:highlighted]];`
    - Class Method: `[AnimationHelper animateView:self.detailStackContainer highlighted:highlighted];`

Unless you have a better idea, I'd say to either change it to a class method or:
1. Remove `AnimationHelper` class altogether
2. Change the animation method to just a public external c method in `AnimationHelpers.h` (add an s to the file name since there could be multiple helper functions

The reason is, we don't really need to allocate a new object in memory to call an animation function.
So, the animation function signature in `AnimationHelpers.h` would look something like this:
```
void AnimateViewHighlightedState(UIView *view, BOOL highlighted);
```
and inside the `setHighlighted:` methods in the tableview/collectionview cells, you'd just call
```
AnimateViewHighlightedState(self.detailStackContainer, highlighted);
```

**Comment by rodericj** [comment]
I’m a big fan/annoying stickler of the imperative mood in commit messages: https://chris.beams.io/posts/git-commit/ has some really great pointers but the voice is important to me. 

Instead of:

> Added so and so whatever

Let’s go with 

> Add so and so whatever


I’ll also ask that you squash this into one commit since it all is heading for the same goal. 

You can do both of these steps with a 

> git rebase -I HEAD~3

Happy to chat if you need me to walk you through it all

**Comment by milesofmichael** [comment]
Going to close the request for now, will try to get the CollectionView to show highlighted state quicker.

**Pull request closed without merging**
